# Generated by Django 5.0.4 on 2024-04-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepic/', verbose_name='Profile Pic'),
        ),
    ]
